version: '3.8'

services:
  postgres: 
    image: postgres:15
    container_name: collab_pg
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: collab_user
      POSTGRES_PASSWORD: collab_pass
      POSTGRES_DB: collab_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: